#! /usr/bin/env sh

NEGRITO=''
ESMAECIDO=''
RESET=''
VERMELHO_NEGRITO=''

if [ -t 1 ]; then
  NEGRITO='\033[1m'
  ESMAECIDO='\033[0;2m'
  RESET='\033[0m'
  VERMELHO_NEGRITO='\033[1;31m'
fi

VERSION=${1}

if [ -z "${VERSION}" ]; then
  echo ""
  echo "${VERMELHO_NEGRITO}Faltou passar a versão da imagem como argumento${RESET}"
  echo ""
  echo "${ESMAECIDO}É para usar assim oh:${RESET}"
  echo ""
  echo "    ${ESMAECIDO}./build-push-merged-image${RESET} ${NEGRITO}0.2.5${NEGRITO}"
  echo ""

  exit 1
fi

docker buildx imagetools create \
  -t "ghcr.io/rwillians/rinha-de-compilers--elixir-transcompiler:latest" \
  -t "ghcr.io/rwillians/rinha-de-compilers--elixir-transcompiler:${VERSION}" \
  "ghcr.io/rwillians/rinha-de-compilers--elixir-transcompiler:${VERSION}-i386" \
  "ghcr.io/rwillians/rinha-de-compilers--elixir-transcompiler:${VERSION}-amd64" \
  "ghcr.io/rwillians/rinha-de-compilers--elixir-transcompiler:${VERSION}-arm64" \
  "ghcr.io/rwillians/rinha-de-compilers--elixir-transcompiler:${VERSION}-armv8" \
  "ghcr.io/rwillians/rinha-de-compilers--elixir-transcompiler:${VERSION}-armv7"
